### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zhayuchuan** [renqabs/ChatSydney-react-img#1]
"Traceback (most recent call last):\n  File \"C:\\ChatSydney-react\\main.py\", line 20, in process_message\n    chatbot = await Chatbot.create(cookies=cookies, proxy=args.proxy)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ChatSydney-react\\EdgeGPT.py\", line 714, in create\n    await _Conversation.create(self.proxy, cookies=cookies),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ChatSydney-react\\EdgeGPT.py\", line 491, in create\n    raise Exception(\"Authentication failed\")\nException: Authentication failed\n"这个怎么解决

**Comment by renqabs** [comment]
这个错误是在绘图还是在正常聊天的时候产生的，你是否使用了cookies.json

**Comment by renqabs** [comment]
如果是在绘图时报的这个错误的话，你需要在web界面中提供_U或者在main.py所在路径存放具有完整cookie的cookies.json文件，
如果是在正常聊天时报了这个错误且使用了cookies.json文件，则需要检查cookie是否可用（可以在官方的bing上聊上一两句），
如果是在正常聊天时报了这个错误且未使用cookies.json文件，我可以尝试通过增加index.html中的异常处理来屏蔽这个弹窗

**Comment by zhayuchuan** [comment]
> 

已经解决了，感谢。是bing官方那里有一个真人验证需要通过

**Comment by zhayuchuan** [comment]
> 如果是在绘图时报的这个错误的话，你需要在web界面中提供_U或者在main.py所在路径存放具有完整cookie的cookies.json文件， 如果是在正常聊天时报了这个错误且使用了cookies.json文件，则需要检查cookie是否可用（可以在官方的bing上聊上一两句）， 如果是在正常聊天时报了这个错误且未使用cookies.json文件，我可以尝试通过增加index.html中的异常处理来屏蔽这个弹窗
额，我是正常聊天他就报这个，我更新了一下cookies.json文件，然后去和官方bing唠了两句，然后过了个真人测试，但他又报错了

**Comment by zhayuchuan** [comment]
如果我要是用index.html启动然后聊天，他就会弹窗显示 {"isTrusted":true}

**Comment by renqabs** [comment]
> 如果我要是用index.html启动然后聊天，他就会弹窗显示 {"isTrusted":true}

本地部署时，需要修改public/index.html下websocket = new WebSocket(`wss://${window.location.host}/ws/`（大概在424行），将wss改为ws，提示{"isTrusted":true}时，可尝试进行修改

**Comment by Pamher123** [comment]
本地部署完成后发现
![image](https://github.com/renqabs/ChatSydney-react-img/assets/143400813/ba8e27f6-1f03-4faa-baf8-7417bfd3ef97)
聊天界面空白，加载不出来，刷新界面后依旧不能加载出来东西，网页图标可以显示
