### ISSUE TITLE
_U cookie是被隐去了吗？

### ISSUE THREAD

**Issue by rswwlhy** [renqabs/ChatSydney-react-img#10]
_U cookie是被隐去了吗？之前用cookie插件直接得到_U cookie，现在没有了，没有_U cookie还怎么用？

**Comment by renqabs** [comment]
![image](https://github.com/renqabs/ChatSydney-react-img/assets/130155002/025f63ac-5cf4-4d1d-a164-b8350e347191)
有的呀，你清理一下cookie或者退出再重新登录试试
