### ISSUE TITLE
页面加载空白

### ISSUE THREAD

**Issue by jishux2** [renqabs/ChatSydney-react-img#11]
控制台和终端报错如下：

![` GK$MCO781W2CM~KU6W`KK](https://github.com/renqabs/ChatSydney-react-img/assets/120390643/822adaed-648a-451a-99d5-22f248535d60)
![K0E $7WXCJUSP$BOSB~{5(Y](https://github.com/renqabs/ChatSydney-react-img/assets/120390643/35b1e973-c8c5-47c0-8315-8e5ad67765d7)

**Comment by renqabs** [comment]
已修复，你再试试

**Comment by jishux2** [comment]
> 关于.map文件的错误暂时没法解决，这个不影响正常使用，map文件只是浏览器用来调试js文件用的，空白页面的问题已修复，你更新一下代码试试

没问题了，感谢大佬
