### ISSUE TITLE
replit报错

### ISSUE THREAD

**Issue by xuyufenfei** [renqabs/ChatSydney-react-img#12]
网页显示authentication failed ，控制台显示status code 404

**Comment by renqabs** [comment]
使用最新的代码试试，我刚部署的，填入_U和KievRPSSecAuth是可以正常用的（有可能需要到官方验证一下账号）
![image](https://github.com/renqabs/ChatSydney-react-img/assets/130155002/e64bdcee-f57a-496c-a836-2854c0017bf3)
