### ISSUE TITLE
图像识别经常返回这两个是什么问题

### ISSUE THREAD

**Issue by d1h1r1** [renqabs/ChatSydney-react-img#13]
![image](https://github.com/renqabs/ChatSydney-react-img/assets/103206466/23c1d4ab-1450-47eb-89ce-d87af7522078)

**Comment by renqabs** [comment]
你直接调用的lib里的EdgeGPT吧，EdgeGPT已经不维护了，现在ChatSydney-react-img项目里单独维护了一份EdgeGPT代码（我试了下图片识别是没问题的），你可以放到你的代码里试试，把EdgeGPT文件夹直接放到你的项目里，代码里增加一行sys.path.insert(0, os.path.dirname(__file__))，如果使用就是我项目里的EdgeGPT，更新下代码再试试
![image](https://github.com/renqabs/ChatSydney-react-img/assets/130155002/80b25445-da34-401c-b124-a3a5958d7b59)

**Comment by d1h1r1** [comment]
好的谢谢，可能应该是newbing内部的问题，现在没有出现了
