### ISSUE TITLE
关于图像上传问题

### ISSUE THREAD

**Issue by Sssssuperior** [renqabs/ChatSydney-react-img#14]
您好，我在原来edgeGPT上增加了您的上传图像模块，await wss.send_str(append_identifier(self.request.struct))在self.request.struct中我看到了message中有输入相应的image_url，且image_url我可以用浏览器打开，但是在给我的回答中却显示他并没有得到这张图片，请问您知道是为什么吗？谢谢

![1703128118684](https://github.com/renqabs/ChatSydney-react-img/assets/75232167/95470928-ebc8-420b-af63-f6134d13c759)

**Comment by renqabs** [comment]
![image](https://github.com/renqabs/ChatSydney-react-img/assets/130155002/aef35e1b-5b98-40c1-b124-0b1a6a1ceac7)
![image](https://github.com/renqabs/ChatSydney-react-img/assets/130155002/59d23cb0-9449-440d-ab74-74fb55f0bf41)
![image](https://github.com/renqabs/ChatSydney-react-img/assets/130155002/bfefd5f1-87a6-4b55-8c96-c6cbe4e89eda)
需要关注的主要是三个地方，conversation_style模块修改参数，conversation模块里获取img_id，request模块里增加self.struct["arguments"][0]["message"]["imageUrl"]参数，你看看是不是都做了修改

**Comment by Sssssuperior** [comment]
嗯嗯，我看了一下是conversation_style没改，改过之后已经能实现功能了，谢谢你！！
