### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by xuyufenfei** [renqabs/ChatSydney-react-img#16]
![IMG_20240302_003950](https://github.com/renqabs/ChatSydney-react-img/assets/133896005/272ebf68-d515-4e77-9a55-1b0158aa06a5)

**Comment by renqabs** [comment]
使用最新的代码试试，我刚在抱脸部署了一下，只填人机验证后的_U值（登录账号，去官网正常对话一次）就可以正常对话

**Comment by xuyufenfei** [comment]
太感谢大佬一直维护这个项目了，如果ui做的好看一些的话，我觉得不输那些大项目

**Comment by renqabs** [comment]
ui搞不了，不太会，python也是半吊子，希望有大佬接手项目
