### ISSUE TITLE
CaptchaChallenge

### ISSUE THREAD

**Issue by yagamilighttuski** [renqabs/ChatSydney-react-img#17]
请问这个CaptchaChallenge问题要怎么解决？
系统：windows10
python：3.11.0
其他：用conda单独弄的一个sydney环境，EdgeGPT版本是0.11.8，cookies.json按链接给的项目拿的
![Snipaste_2024-03-18_21-37-50](https://github.com/renqabs/ChatSydney-react-img/assets/78994336/0ea35b68-36f7-47f2-b657-8afdaa1d2a1c)

**Comment by renqabs** [comment]
![image](https://github.com/renqabs/ChatSydney-react-img/assets/130155002/7c10e319-c198-4ba7-8894-676882f88a56)
参考下这个项目里的这个文件，把header里相关部分改成移动端的值，暂时可以绕过CaptchaChallenge，当前项目还没来得及修改
