### ISSUE TITLE
尝试进行对话时报错

### ISSUE THREAD

**Issue by WarnError** [renqabs/ChatSydney-react-img#2]
提示
"Traceback (most recent call last):\n  File \"/data/data/com.termux/files/home/ChatSydney-react-img/main.py\", line 25, in sydney_process_message\n    async for _, response in chatbot.ask_stream(prompt=user_message, conversation_style=\"creative\", raw=True,\n  File \"/data/data/com.termux/files/home/ChatSydney-react-img/EdgeGPT.py\", line 816, in ask_stream\n    async for response in self.chat_hub.ask_stream(\n  File \"/data/data/com.termux/files/home/ChatSydney-react-img/EdgeGPT.py\", line 668, in ask_stream\n    raise Exception(\nException: CaptchaChallenge: User needs to solve CAPTCHA to continue.\n"
这个验证码问题如何解决？

**Comment by renqabs** [comment]
出现这个问题的话，目前只能使用完整的cookie即使用cookies.json，等切换到SydneyGPT库时可解决此问题（SydneyGPT库目前的画图功能存在问题，不使用cookie也是可以进行正常对话的）

**Comment by renqabs** [comment]
我已经给EdgeGPT的作者提交画图的bug了，估计会修的吧，我本地改了下代码，修改后就可以正常画图和无cookie对话了

**Comment by WarnError** [comment]
> 出现这个问题的话，目前只能使用完整的cookie即使用cookies.json，等切换到SydneyGPT库时可解决此问题（SydneyGPT库目前的画图功能存在问题，不使用cookie也是可以进行正常对话的）

已经知道解决方法了，要去对应网站上完成机器人验证

**Comment by zhayuchuan** [comment]
> > 出现这个问题的话，目前只能使用完整的cookie即使用cookies.json，等切换到SydneyGPT库时可解决此问题（SydneyGPT库目前的画图功能存在问题，不使用cookie也是可以进行正常对话的）
> 
> 已经知道解决方法了，要去对应网站上完成机器人验证

去哪个网站验证啊，我在bing验证之后还是报错

**Comment by renqabs** [comment]
现在已经切换到sydneyGPT库，使用最新代码再试试，应该不会有这个错误了
