### ISSUE TITLE
在海外vps上部署docker 报错

### ISSUE THREAD

**Issue by huoshenw** [renqabs/ChatSydney-react-img#3]
Error handling request
chatsydney  | Traceback (most recent call last):
chatsydney  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
chatsydney  |     messages, upgraded, tail = self._request_parser.feed_data(data)
chatsydney  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatsydney  |   File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
chatsydney  | aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
chatsydney  | Error handling request
chatsydney  | Traceback (most recent call last):
chatsydney  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
chatsydney  |     messages, upgraded, tail = self._request_parser.feed_data(data)
chatsydney  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatsydney  |   File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
chatsydney  | aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
chatsydney  | Error handling request
chatsydney  | Traceback (most recent call last):
chatsydney  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
chatsydney  |     messages, upgraded, tail = self._request_parser.feed_data(data)
chatsydney  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatsydney  |   File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
chatsydney  | aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
chatsydney  | Error handling request
chatsydney  | Traceback (most recent call last):
chatsydney  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
chatsydney  |     messages, upgraded, tail = self._request_parser.feed_data(data)
chatsydney  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatsydney  |   File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
chatsydney  | aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
在根目录放入cookies.json文件后，docker-compose up，访问网页提问后报错

**Comment by renqabs** [comment]
我也没在vps上部署过，我刚在render平台使用docker重新部署了一下，不使用cookie也可以的，我docker部署一般用的是dockfile，估计是docker-compose.yaml的问题吧，我对compose也不是很熟悉。。。，只能尝试一下了

**Comment by huoshenw** [comment]
"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py\", line 662, in __await_impl__\n    await protocol.handshake(\n  File \"/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py\", line 329, in handshake\n    raise InvalidStatusCode(status_code, response_headers)\nwebsockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/sit 按照你的教程在render部署后这样 如果要在dockerfile构建镜像用什么命令 小白不太懂。。

**Comment by renqabs** [comment]
> "Traceback (most recent call last):\n File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 662, in **await_impl**\n await protocol.handshake(\n File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 329, in handshake\n raise InvalidStatusCode(status_code, response_headers)\nwebsockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/usr/local/lib/python3.11/sit 按照你的教程在render部署后这样 如果要在dockerfile构建镜像用什么命令 小白不太懂。。

应该是EdgeGPT库出了问题，早上的时候我部署的网站也突然都出现问了，暂时用不了了，我找时间修修

**Comment by huoshenw** [comment]
用dokcerfile构建后 在网页上提问 显示{"isTrusted":true}

**Comment by huoshenw** [comment]
Proxy used: None
Loaded cookies.json
Go to http://0.0.0.0:65432 to start chatting!
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"

**Comment by huzw1995** [comment]
> > "Traceback (most recent call last):\n File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 662, in **await_impl**\n await protocol.handshake(\n File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 329, in handshake\n raise InvalidStatusCode(status_code, response_headers)\nwebsockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/usr/local/lib/python3.11/sit 按照你的教程在render部署后这样 如果要在dockerfile构建镜像用什么命令 小白不太懂。。
> 
> 应该是EdgeGPT库出了问题，早上的时候我部署的网站也突然都出现问了，暂时用不了了，我找时间修修

靠你了，我也遇到和这一样的问题了
