### ISSUE TITLE
请问如何上传图片

### ISSUE THREAD

**Issue by wh-yu** [renqabs/ChatSydney-react-img#4]
您好, 您的repo非常的棒, 非常感谢.

请问如何上传图片, 

```python
image_path =  'image.png'
# method 1
imageInput = image_path
# method 2
imageInput = open(image_path, 'rb').read()
bot = await Chatbot.create(imageInput=image)
```

method 1和method 2都报错 "Exception: Authentication failed".

谢谢您!

**Comment by wh-yu** [comment]
感谢! 看了您的代码, 原来要输入imageBase64, 问题已经解决, 感谢!

**Comment by renqabs** [comment]
> 感谢! 看了您的代码, 原来要输入imageBase64, 问题已经解决, 感谢!
图片好像要压缩一下，应该不能超过1M

**Comment by wh-yu** [comment]
> > 感谢! 看了您的代码, 原来要输入imageBase64, 问题已经解决, 感谢!
> > 图片好像要压缩一下，应该不能超过1M

好的, 感谢
