### ISSUE TITLE
使用termux部署，聊天时出现问题

### ISSUE THREAD

**Issue by xuyufenfei** [renqabs/ChatSydney-react-img#5]
![Screenshot_2023-07-30-02-17-07-558_com lemurbrowser exts](https://github.com/renqabs/ChatSydney-react-img/assets/133896005/9cbc8f94-41b6-4367-9f50-b527e700392c)

**Comment by renqabs** [comment]
我在termux部署后是没问题的，我随便输入一串错误的cookie都可以正常对话，可能是你的cookie出问题了

**Comment by xuyufenfei** [comment]
谢谢老哥，应该是我的账号被ban了
