### ISSUE TITLE
在服务器上使用docker部署显示{"isTrusted":true}

### ISSUE THREAD

**Issue by xuyufenfei** [renqabs/ChatSydney-react-img#7]
Proxy used: None
cookies.json not found
Go to http://0.0.0.0:65432 to start chatting!
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Bad status line "Invalid method encountered:\n\n  b'\\x16\\x03\\x01\\x02'\n    ^"
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Bad status line "Invalid method encountered:\n\n  b'\\x16\\x03\\x01\\x02'\n    ^"

**Comment by renqabs** [comment]
如果没使用https代理的话，需要修改下public/index.html下的代码，将487行的wss改为ws

**Comment by xuyufenfei** [comment]
![IMG_20230813_231455](https://github.com/renqabs/ChatSydney-react-img/assets/133896005/f413ee84-e4b1-4307-9864-c4ab4c8d2b1f)

**Comment by xuyufenfei** [comment]
![IMG_20230813_231502](https://github.com/renqabs/ChatSydney-react-img/assets/133896005/98ac156b-a75d-495f-88e2-4e709a348ed0)

**Comment by renqabs** [comment]
更新一下代码再试试，Sydney模块已经被移除了

**Comment by xuyufenfei** [comment]
![Screenshot_2023-08-14-23-53-43-184_com.microsoft.emmx.jpg](https://github.com/renqabs/ChatSydney-react-img/assets/133896005/ab5e9a4b-3c0d-4d31-830d-1899cea691b7)

**Comment by xuyufenfei** [comment]
![Screenshot_2023-08-15-00-32-21-361_com.microsoft.emmx.jpg](https://github.com/renqabs/ChatSydney-react-img/assets/133896005/cc9359a9-78d4-4d45-aaa4-fd033c1cc54b)

**Comment by xuyufenfei** [comment]
感觉termux好部署的多啊，cookie随便填都没关系

**Comment by renqabs** [comment]
服务器IP可能被禁了

**Comment by xuyufenfei** [comment]
大佬，可以通过挂clash解决吗

**Comment by renqabs** [comment]
应该可以的，我本地用clash是没问题的，前提是节点没被禁

**Comment by xuyufenfei** [comment]
这个本来是clash的,我把配置导入到了服务器的v2,手机上这个节点配置是可以用的

**Comment by xuyufenfei** [comment]
实在不行的话可以通过配置代理地址解决吗

**Comment by xuyufenfei** [comment]
再不行我试试在在render上部属

**Comment by renqabs** [comment]
render上可以用的，比较稳定

**Comment by xuyufenfei** [comment]
谢谢大佬，我在replit上部署成功了

**Comment by renqabs** [comment]
> 谢谢大佬，我在replit上部署成功了
不好用的时候，重新部署或者重启几次可能就好了

**Comment by xuyufenfei** [comment]
replit也提示我未通过测试版，但填入正确的cookie就可以了,服务器怎么填都不行,太奇怪了
