### ISSUE TITLE
本地部署完成之后页面一直是空白的

### ISSUE THREAD

**Issue by Pamher123** [renqabs/ChatSydney-react-img#9]
![image](https://github.com/renqabs/ChatSydney-react-img/assets/143400813/c113b109-7cca-4955-8b19-fb8a7b491097)
刷新了也没用，还是空白页面，什么都没有

**Comment by renqabs** [comment]
本地部署时，需要修改public/index.html下websocket = new WebSocket(wss://${window.location.host}/ws/（大概在498行），将wss改为ws，这个改了吗，我刚本地运行了下没问题的呀（需要魔法）

**Comment by Pamher123** [comment]
改过了的
![image](https://github.com/renqabs/ChatSydney-react-img/assets/143400813/f3615111-fb25-4c80-9dda-2ba884d023c3)
现在还是空白
![image](https://github.com/renqabs/ChatSydney-react-img/assets/143400813/e4fc8196-9ca3-4cb0-a676-1ae64c2a0dcc)
mo'fa'shang'w魔法上网也是有的
![image](https://github.com/renqabs/ChatSydney-react-img/assets/143400813/37089d9b-dede-4f82-bfb9-05b91ca63144)

**Comment by renqabs** [comment]
![image](https://github.com/renqabs/ChatSydney-react-img/assets/130155002/3f17ee30-d877-4623-a6c0-044b0c6b7a07)
你看下控制台里有没有什么报错

**Comment by Pamher123** [comment]
![image](https://github.com/renqabs/ChatSydney-react-img/assets/143400813/6114311a-c829-412e-b2e7-c7c497be8021)
好像是有的

**Comment by Pamher123** [comment]
另外发现shell里面
![image](https://github.com/renqabs/ChatSydney-react-img/assets/143400813/4aa00f5b-c2ae-490c-9dd5-463826514a55)

**Comment by renqabs** [comment]
![image](https://github.com/renqabs/ChatSydney-react-img/assets/130155002/124c60f0-9a6c-4805-b319-dfd3dc0a64c4)
你看下网络里tts.js那个，看看server的响应类型是什么，我这返回类型是没问题的，或者更新一下依赖试试

**Comment by renqabs** [comment]
map文件不存在的提示不用管，这个不影响使用

**Comment by Pamher123** [comment]
![image](https://github.com/renqabs/ChatSydney-react-img/assets/143400813/edc586ec-90b7-4ff2-8a70-cc35f1a7bb00)
![image](https://github.com/renqabs/ChatSydney-react-img/assets/143400813/e3cf5a1d-06d5-492e-a94c-065a73ce5ac1)
还是不行

**Comment by renqabs** [comment]
难道aiohttp版本太新了？我用的python3.10 aiohttp/3.8.4

**Comment by Pamher123** [comment]
我python是今天才去官网安装的，应该是最新的

**Comment by renqabs** [comment]
![image](https://github.com/renqabs/ChatSydney-react-img/assets/130155002/f23231f5-9d42-4827-a1a5-70d1af5d277f)
我这换成了跟你一样的环境，没问题呀，你要不试试重装下aiohttp模块

**Comment by Pamher123** [comment]
我试试

**Comment by Pamher123** [comment]
是要卸载掉本地库然后重新执行安装库指令是吧

**Comment by renqabs** [comment]
pip uninstall aiohttp然后再执行pip install aiohttp

**Comment by Pamher123** [comment]
![image](https://github.com/renqabs/ChatSydney-react-img/assets/143400813/52c3d0ef-696f-4d99-a5d7-627412a3f8f7)
![image](https://github.com/renqabs/ChatSydney-react-img/assets/143400813/04f8ea7e-12f9-4b79-8c76-a35ea5aecd5f)
没有解决

**Comment by renqabs** [comment]
![image](https://github.com/renqabs/ChatSydney-react-img/assets/130155002/e2c15bde-2ee7-4656-87ca-9633b6519301)
![image](https://github.com/renqabs/ChatSydney-react-img/assets/130155002/291fcf27-467b-453d-9aa6-bbb5ef2bf3d0)

你的python是64位的吗

**Comment by renqabs** [comment]
我更新成了python 3.11.5,运行也是正常的，太奇怪了

**Comment by Pamher123** [comment]
这个项目的本地服务器文件是哪一个？newbing给我的回答是我可以根据本地服务器文件去设置一下MIME类型

**Comment by renqabs** [comment]
根目录main.py，使用的aiohttp，Content-Type默认是自动设置的

**Comment by Pamher123** [comment]
您好今天我尝试部署成功了，我不知道为什么就突然成功了，但是有时候对话会触发Message revoke detected该怎么办

**Comment by Pamher123** [comment]
已经解决了

**Comment by Pamher123** [comment]
![image](https://github.com/renqabs/ChatSydney-react-img/assets/143400813/222b8b47-c173-4842-b793-2ecadc16c5ec)
昨晚在遇到不停要求身份验证之后重新部署，但是发现部署之后网页打不开了

**Comment by Pamher123** [comment]
解决了，原来是我用的是https不是http
